name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Build Project
        run: |
          npm install --legacy-peer-deps
          npm run build
        env:
            CI: false

      - name: Log in to GitHub Container Registry
        env:
            PAT: ${{ secrets.PAT }}
        run: echo "$PAT" | docker login ghcr.io -u h1ddenscript --password-stdin

      - name: Build Docker image
        run: |
          REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          BRANCH_NAME=$(echo ${{ github.ref_name }} | tr '[:upper:]' '[:lower:]')
          docker build . -t ghcr.io/$REPO_LOWER/portfolio:$BRANCH_NAME

      - name: Push Docker image to GitHub Packages
        run: |
          REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          BRANCH_NAME=$(echo ${{ github.ref_name }} | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$REPO_LOWER/portfolio:$BRANCH_NAME